# Railway will auto-detect PHP based on composer.json
# This file specifies the PHP version for Railway
providers = ["php"]

[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."
